### ISSUE TITLE
Add email to user identity

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#105]
When a user submits an application, the user identity should contain the email that the application confirmation is sent to.

**Comment by taesungh** [comment]
Sorry for the confusion, we actually already have this in [user_identity](https://github.com/HackAtUCI/irvinehacks-site-2024/blob/main/apps/api/src/auth/user_identity.py), will be incorporated as part of #93.
```python
class User(BaseModel):
    uid: str
    email: EmailStr
```
Reason I originally mentioned was because last year's application had a redundant email field which we removed this year
